---

- name: run apt-get update
  hosts: tag_ds_Yes
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  tasks:
    - apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9
    - command: apt-get update    

        
- name: Setup packages
  hosts: tag_ds_Yes
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
  tasks:
      - apt: pkg={{item}} state=installed allow_unauthenticated=yes
        with_items:
             - git
             - build-essential
             - sudo
             - wget
             - gdebi-core
             - emacs24
             - openjdk-8-jdk
             - mosh
             - htop
            
   
      - user: name=carsten comment="Carsten Behring" groups=sudo password="$6$/4z0WSR40MY$2w488iVd3jdeGOTh0RlMrr4bSOcJlUesLIP3GWwHgpl4hCDV0Gil0YnLNuMFDtk6RXlmy83HOOUZlNGky5ybg1"
      - command: pip install --upgrade pip   
      - pip: name={{item}}
        with_items:
          - jupyter     
  
  roles:
    
    
 
- name: R and packages
  hosts: tag_ds_Yes
  sudo: yes 
  remote_user: ubuntu
  vars:
    r_packages:
      - name: pacman
      - name: tidyverse
    r_install:
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev
  roles:
    - tersmitten.r  
    - tersmitten.rstudio
 

              
- name: Setup data for carsten
  hosts: tag_ds_Yes
  remote_user: ubuntu
  become: yes
  become_user: carsten 
  vars:
    miniconda_home: /home/carsten/miniconda
    git_config:
       user:
         name: Carsten Behring
         email: carsten.behring@gmail.com 

  tasks:
     - git: repo=https://github.com/behrica/emacs.d dest=/home/carsten/.emacs.d update=yes
     - file: path=/home/carsten/sources state=directory
  roles:
     -  nicholsn.miniconda  
     -  kosssi.gitconfig  
     #-  dominoClient   
       
