---
- name: run apt-get update
  hosts: tag_ds_Yes
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  tasks:
  #  - apt_repository: repo='deb http://cran.r-project.org/bin/linux/ubuntu trusty/' state=present
    - apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9
    - command: apt-get update    

        
- name: Setup packages
  hosts: tag_ds_Yes
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
  tasks:
      - apt: pkg={{item}} state=installed allow_unauthenticated=yes
        with_items:
             - git
             - build-essential
             - sudo
             - wget
            # - mc
             - r-base
             - gdebi-core
            # - python-pip
            # - libzmq-dev
            # - python-dev
             - openjdk-8-jdk
            # - libcurl4-openssl-dev
            # - libssl-dev
            # - libxml2-dev
   
      - user: name=carsten comment="Carsten Behring" groups=sudo password="$6$/4z0WSR40MY$2w488iVd3jdeGOTh0RlMrr4bSOcJlUesLIP3GWwHgpl4hCDV0Gil0YnLNuMFDtk6RXlmy83HOOUZlNGky5ybg1"
      - command: pip install --upgrade pip   
      - pip: name={{item}}
        with_items:
          - jupyter     
  
  roles:
    #- inadyn
    #- jdauphant.dropbox
    #- jasonj.sudoers

- name: install dev tools
  hosts: tag_ds_Yes
  sudo: yes 
  remote_user: ubuntu
  vars:
    clojure_versions: ["1.7.0"]             # A list of clojure versions you want to have installed
    clojure_default_version: "1.7.0"        # The clojure version you want to be the system default
    clojure_leiningen_version: "2.5.3"      # The version of leiningen to install
  roles:
    #- ANXS.clojure


  
- name: R and packages
  hosts: tag_ds_Yes
  sudo: yes 
  remote_user: ubuntu
  vars:
    r_packages:
      - name: pacman
      - name: dplyr
      - name: ggplot2
  roles:
    - tersmitten.r  
   # - emacs24
    - rstudio
 

              
- name: Setup data for carsten
  hosts: tag_ds_Yes
  remote_user: ubuntu
  become: yes
  become_user: carsten 
  vars:
    miniconda_home: /home/carsten/miniconda
    git_config:
       user:
         name: Carsten Behring
         email: carsten.behring@gmail.com 

  tasks:
     - git: repo=https://github.com/behrica/emacs.d dest=/home/carsten/.emacs.d update=yes
     - file: path=/home/carsten/sources state=directory
  roles:
     #-  nicholsn.miniconda  
     #-  kosssi.gitconfig  
     -  dominoClient   
       
