- name: test one role on EC2
  hosts: tag_ds_Yes
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
  roles:
    -  nicholsn.miniconda
