---
# Based heavily on the Ansible documentation on EC2:
# http://docs.ansible.com/ec2_module.html
- name: Provision an EC2 node
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  vars:
      instance_type: t2.small
      security_group: ds 
      image: ami-47a23a30 
      region: eu-west-1 
      keypair: ansible
  tasks:
      - name: Launch new Instance
        local_action: ec2 instance_tags="ds=Yes" group={{ security_group }} instance_type={{ instance_type}} image={{ image }} wait=true region={{ region }} keypair={{ keypair }} vpc_subnet_id=subnet-50b2ca35 assign_public_ip=yes exact_count=1 count_tag=ds
        register: ec2

  
      - name: Wait for SSH to come up
        local_action: wait_for host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
        with_items: ec2.instances


      - name: Add all instance public IPs to host group
        add_host: hostname={{ item.public_ip }} groups=tag_ds_Yes
        with_items: ec2.instances
               
- name: run apt-get update
  hosts: tag_ds_Yes
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  tasks:
      - command: apt-get update    

        
- name: With the newly provisioned EC2 node configure that thing
  hosts: tag_ds_Yes
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
  tasks:
      - apt_repository: repo='deb http://cran.r-project.org/bin/linux/ubuntu trusty/' state=present
      - apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9
      - apt: pkg={{item}} state=installed
        with_items:
            - git
            - build-essential
            - mosh
            - mc
            - r-base
            - gdebi-core
            - python-pip
            - libzmq-dev
            - python-dev
            - openjdk-7-jdk
            - libcurl4-openssl-dev
            
      - apt: pkg=emacs24 state=build-dep
      - user: name=carsten comment="Carsten Behring" password="$6$/4z0WSR40MY$2w488iVd3jdeGOTh0RlMrr4bSOcJlUesLIP3GWwHgpl4hCDV0Gil0YnLNuMFDtk6RXlmy83HOOUZlNGky5ybg1"
      - command: pip install --upgrade pip   
      - pip: name={{item}}
        with_items:
          - rodeo
          - traitlets
          - simplegeneric
          - pexpect
          - pickleshare
          - ipykernel
          - jupyter     
  roles:
    - inadyn
    - jdauphant.dropbox
    
- name: install emacs 24 from source
  hosts: tag_ds_Yes
  remote_user: ubuntu
  tasks:
    - get_url: url=http://mirrors.kernel.org/gnu/emacs/emacs-24.4.tar.xz dest=/tmp/emacs-24.4.tar.xz
    - unarchive: src=/tmp/emacs-24.4.tar.xz  dest=/tmp copy=no creates=/tmp/emacs-24.4/README
    - command: ./configure chdir=/tmp/emacs-24.4 creates=/tmp/emacs-24.4/Makefile  
    - command: make chdir=/tmp/emacs-24.4 creates=/tmp/emacs-24.4/src/emacs
    - command: sudo make install chdir=/tmp/emacs-24.4 creates=/usr/local/bin/emacs-24.4
        


- name: install rstudio
  hosts: tag_ds_Yes
  remote_user: ubuntu
  tasks:
    - shell: wget -O /tmp/rstudio-server-0.99.489-amd64.deb https://download2.rstudio.org/rstudio-server-0.99.489-amd64.deb creates=/tmp/rstudio-server-0.99.489-amd64.deb
    - command: sudo gdebi -n /tmp/rstudio-server-0.99.489-amd64.deb creates=/usr/lib/rstudio-server/bin/rserver
 

              
- name: Setup data for carsten
  hosts: tag_ds_Yes
  remote_user: ubuntu
  become: yes
  become_user: carsten 
  vars:
    miniconda_home: /home/carsten/miniconda

  tasks:
     - git: repo=https://github.com/behrica/emacs.d dest=/home/carsten/.emacs.d update=yes
     - name: download domino
       shell: wget -O /tmp/domino-install-unix.sh http://static.dominodatalab.com/cloud/domino-install-unix.sh creates=/tmp/domino-install-unix.sh
     - file: path=/tmp/domino-install-unix.sh  mode="o+x,g+x,u+x"
     - name: install domino  
       command: /tmp/domino-install-unix.sh -q creates=/home/carsten/domino/domino
     - file: path=/home/carsten/.dominoconfig state=directory
     - template: src=templates/dominoConfig.j2 dest=/home/carsten/.dominoconfig/install_config.json 
     - file: path=/home/carsten/sources state=directory
  roles:
     -  nicholsn.miniconda  
       
