- name: download domino
  shell: wget -O /tmp/domino-install-unix.sh http://static.dominodatalab.com/cloud/domino-install-unix.sh creates=/tmp/domino-install-unix.sh
- file: path=/tmp/domino-install-unix.sh  mode="o+x,g+x,u+x"
- name: install domino  
  command: /tmp/domino-install-unix.sh -q creates=/home/carsten/domino/domino
- file: path=/home/carsten/.dominoconfig state=directory
- template: src=dominoConfig.j2 dest=/home/carsten/.dominoconfig/install_config.json 
