# tasks file for r
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: r_dependencies
  when: "item | trim != ''"
  tags:
    - r-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: latest
  with_items: r_install
  tags:
    - r-install-additional
